version: "2" 
services: 
###########################################
###### Clinical data Workflow        ######
###########################################
  data_postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  rdf_store:
    image: jvsoest/graphdb-free:8.4.1
    ports: 
      - "7200:7200"
    volumes:
      - ./graphdb_template/:/opt/graphdb/home/
  r2rml:
    image: jvsoest/r2rml
    links:
      - data_postgres:dbhost
      - rdf_store:graphdb
  notebook:
    build:
      context: notebooks
    ports:
      - "8888:8888"
      - "8088:8088"
    volumes:
      - ./notebooks:/queries/
    links:
      - data_postgres:postgresdb
      - rdf_store:graphdb
  oraw:
    image: jvsoest/oraw
    volumes:
      - C:/Users/johan/VARIAN_VATE/:/data/
    links:
      - rdf_store:graphdb
    environment:
      - RDF4J_URL=http://graphdb:7200
      - EXCLUDE_STRUCTURE_REGEX="(Patient.*|BODY.*|Body.*|NS.*|Couch.*|Isocenter.*)"
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  192.169.230.1/24
